name: Build

on: [push, pull_request]

jobs:
  build-cmake:
    strategy:
      fail-fast: false
      matrix:
        include:
            - name: Windows
              os: windows-latest
            - name: Ubuntu
              os: ubuntu-latest
            - name: MacOS
              os: macOS-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Prepare cmake
      uses: lukka/get-cmake@latest

    - name: Run vcpkg
      if: matrix.android == 'none'
      uses: lukka/run-vcpkg@v11

    - name: Prepare Ubuntu
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt update -y
        sudo apt install cmake -y

    - name: Config cmake(Ubuntu&MacOS)
      run: ${{ matrix.cmake-path }}cmake --preset=default

    - name: Build under PC
      run: ${{ matrix.cmake-path }}cmake --build cmake-build
